# Generated by Django 3.2.7 on 2021-12-26 14:50

from django.db import migrations, models
import django.db.models.deletion
import organization.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=256, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=organization.models.employee_directory_path, verbose_name='Фото')),
                ('post', models.CharField(blank=True, max_length=256, null=True, verbose_name='Должность')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Зарплата')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organization.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employee',
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name'], name='employee_last_na_c35afb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('id', 'department')},
        ),
    ]
